Vagrant.require_version ">= 1.7.0"


Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  # these will only work if you are configuring nginx
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 443, host: 9443
  # these won't work if you are binding to localhost
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 9001, host: 9001
  # es access
  config.vm.network "forwarded_port", guest: 9200, host: 9200

  config.vm.provision "file", source: "../local_config.json", destination: "/tmp/local_config.json"

  # Need Git to install non-galaxy requirements..
  config.vm.provision :shell, inline: <<-END
      /usr/bin/yum install -y git
  END

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "v"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.playbook = "playbook.yml"
  end
end
